### ISSUE TITLE
Архитектура приложения

### ISSUE THREAD

**Issue by Vladislav-wn** [MaksymGrom/ng-blog#11]
Добрый день!
Может быть не совсем по теме, так что если не ответите - пойму. 
Например, я хочу разделить проект на несколько приложений. Т.е - есть корневой проект Angular - Apps и в нем три приложения Angular:  блог - App1, админ - App2, прочее - App3.  При этом, App1 сразу загружается  при заходе на сайт, а App2 и App3, только в тот момент, когда нажал соответствующую кнопку главного меню, пусть - "Админ" и "Прочее".  Т.е - главное меню служит для перехода между приложениями (App1, App2, App3) , а внутри каждого приложения свое "локальное" меню. 
Вопрос: как строить навигацию между приложениями и какова "примерно" архитектура такого проекта (может быть нужно делать классический проект на HTML с тремя страницами (Блог, Админ, Прочее), а уже в каждую из этих страниц HTML встраивать соответствующее приложение Angular?)  
Цель: пытаюсь понять, как разделить проект и тем самым уменьшить объем загрузки?. Спасибо :-)

**Comment by MaksymGrom** [comment]
А вы уверены что это должно быть 3 независимых приложения? 
Если приложения независимые то можно изолировать настройки di для каждого проекта отдельно, однако переход будет с перезагрузкой, шаринг состояния это будет постоянно больно.
Можно сделать lasy loading через ng routing. Т.е. При первом заходе будет загружен только логин модуль, при логине будет догружен админ модуль, а при заходе на части фрогтенда будут подгружаться остальные части. Все упадет в кеш браузера и второй раз не бужут грузится. Я буду это делать в этом курсе(вторую схему). Однако тут минус в том, если есть реализация логина абстрактная, то просто подменить ее не получится, так как и фронтенд и админ будут загружены, т.е. Надо будет пользоваться сервисами по типу LoginService, AdminLoginService либо изолировать di на уровне компонентов, но тогда теряются возможности настройки через модули для переопределенных зависимостей

**Comment by Vladislav-wn** [comment]
Понял, спасибо!

**Comment by MaksymGrom** [comment]
https://www.youtube.com/watch?v=uBuOaDRq5JU
Снял свои мысли по этому вопросу, закрываю задачку :)
